apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    app: newimage
  ports:
     - protocol: TCP
       port: 80
       targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-svc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: newimage
  template:
    metadata:
      labels:
        app: newimage
    spec:
      containers:
        - name: newimage
          image: ssukumar27/newimage:latest
          imagePullPolicy: Always
          ports:
           - containerPort: 8080  
